---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ldschurch-stream-secrets
  namespace: ldschurch-stream
spec:
  encryptedData:
    mongodb_password: AgBl+sQG/ELH2omvNFB3wDni3nUzEqa4rrrDx7yde6rzLatyqKNSz/dRo+1HB2FYbl3VuXqUbD1PFizQZe4L9JuF/FwtvDGNeo2wBsbQ3ROJrtPSEAZ4nk6aC8BQxijlepNWsNDIal2iq9j6/Cfai8/oFVIsUK7GgOMR01kjhnw3fNNJVrM6QflDSfkLt+epXqux11eaPhoUU+jgcjtYd1yQ2O2kKZJeFsYFMFII+SwRy6ztL8W4PQG1HmPzL+H9Bo/v9XcMOO+LlVwVL6ek+x54M8Py69HISJc3DGhxzdHQhHX3xi4zrE4m17lhyX2scg6xOaEQIvY8zPY/QqJ59R+PfaiYbFbptD/wacsTMqfebdIROLY9kxYivx1683v2Dur/pW6s8juyHyRJgcWd+rYUweYXE3BxeKk194CMTJEPG1N4VKWEBC6QtKuVGTpxncvr6r5wLJFuvW6xJLz6c/qrVcqC84HUegBnP2BnLpIz4qsTBMzh9YcGcgW/pIwK/cbYzXBEU++qvFqx4J6KmYXWekz8thXf7bUvZ4Fk47w3xYrqWDxEir6692+EGZrhWUVL0m6P044XFAY9SlWHTH4Qr/HuhZxILmwpjiCYi50ZXdpZvycnsxDFWVvxha/nVfVWFxUExzIlzYcpV+4FbV2xbT9BMbLnwS1iGZEVJv5OORBFY48QiTZZlojv7lT3evYye/pOPGTu3Pl1vWGHZH3HvU3Ee/j9uuT5w/Ha81CTLq/0QOU=
  template:
    metadata:
      creationTimestamp: null
      name: ldschurch-stream-secrets
      namespace: ldschurch-stream
    type: Opaque
